Algoritmo "exemplo_para"

Var

   num:inteiro
   quantidade_numero:inteiro
   soma:inteiro
   cont:inteiro



Inicio

   soma <- 0

   escreval("Digite quantos numeros você deseja: ")
   leia(quantidade_numero)

   para cont de 1 ate quantidade_numero faca

      escreval("Digite um numero: ")
      leia(num)

      soma <- soma + num

   fimpara
   
   
    escreval("SOMA = ", soma)




Fimalgoritmo