Algoritmo "media_ponderada"

Var
   casos,cont:inteiro
   n1,n2,n3,media:real


Inicio


   escreva("Quantos casos voce vai digitar?: ")
   leia(casos)

   para cont de 1 ate casos faca

      escreva("Digite o valor primeiro numero: ")
      leia(n1)

      escreva("Digite o valor segundo numero: ")
      leia(n2)

      escreva("Digite o valor terceiro numero: ")
      leia(n3)

      media <- (n1+n2+n3)/3

       escreval("MÉDIA = ", media:2:2)

   fimpara









Fimalgoritmo